name: Collect Statistics

on:
  workflow_dispatch:
  schedule:
    - cron: "* 5-23 * * *"
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: "Install python dependencies"
        run: python -m pip install -r requirements.txt
      - name: "Run python scraper"
        run: python scraper.py
      - name: "Deploy files"
        run: |
          git config --global user.email "thom.florian@yahoo.de"
          git config --global user.name "FlorianTh2"
          git add -A
          git commit -a -m "chore: update stats from $(date +%s)"
          git push origin HEAD:main
